lsi: false
safe: false
source: tads-ifpruniao/
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Tecnólogo em Análise e Desenvolvimento de Sistemas
description: Página do Curso TADS do Campus União da Vitória do Instituto Federal do Paraná
show_downloads: false
